# Generated by Django 4.2.7 on 2023-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('fullBio', models.TextField()),
                ('profileImage', models.ImageField(upload_to='images/')),
                ('resumeURL', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
