# Generated by Django 4.2.7 on 2023-11-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('url', models.URLField()),
            ],
        ),
    ]
