# Generated by Django 4.2.7 on 2023-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_project_description_project_logo_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
