# Generated by Django 4.2.7 on 2023-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_project_name_project_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
