# Generated by Django 4.2.7 on 2023-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_project_projecturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='fallback_images/'),
        ),
    ]
