# Generated by Django 4.2.7 on 2023-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_technology_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
