# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_project_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(default='Default description')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='App.skill'),
        ),
    ]
