# Generated by Django 4.2.7 on 2023-11-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_skills_profile_skill_alter_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='skills',
        ),
    ]
