# Generated by Django 4.2.7 on 2023-11-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
